name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        run: |
          mkdir -p public/.well-known
          cp -r .well-known public/
          touch public/.nojekyll
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add public/
          git commit -m "Force deploy .well-known"
          git push origin main
